#!/usr/bin/env bash
# Configure Nginx server to redirect to another page

ADD301_REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx start
