#!/usr/bin/env bash
#install nginx on web server

ADD_HEADER="\\\tadd_header X-Served-By $HOSTNAME;"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start

sudo sed -i "27i $ADD_HEADER" /etc/nginx/sites-available/default

sudo service nginx restart
