#!/usr/bin/env bash
# configure HAproxy with given config settings

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get update
sudo apt-get -y install haproxy=2.0\*
sudo  sed -i "s/ENABLED=0/ENABLED=1/" /etc/default/haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.back
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\t server 3951-web-01 35.231.224.50:80 check\n\tserver 3951-web-02 54.211.197.188:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart

