#!/usr/bin/env bash
# display "Best school" 10 times but in the 9th iteration display "hi"
i=1
while [ "$i" -le 10 ]
do
    echo "Best School"
    if [ "$i" -eq 9 ]; then
	echo "Hi"
    fi
    (( i++ ))
done
