#!/usr/bin/env bash
# prints "bad luck" in 4th iteration, "good luck" in the 8th, and "best school"
# in the rest
i=0
while [ $i -lt 10 ]
do
  if [ $i -eq 3 ]; then
    echo "bad luck"
  elif [ $i -eq 7 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((i++))
done
