#!/usr/bin/env bash
# using case and while display numbers from 1 to 20 with some execptions
i=1
while [ $i -lt 21 ]
do
  case $i in
    4)
      echo "4"
      echo "bad luck from China"
      ;;
    9)
      echo "9"
      echo "bad luck from Japan"
      ;;
    17)
      echo "17"
      echo "bad luck from Italy"
      ;;
    *)
      echo $i
      ;;
  esac
  ((i++))
done 
