#!/usr/bin/env bash
# make a clock that display all hours and minutes
i=0
j=1
while [ $i -le 12 ]
do
  echo "hour: $i"
  while [ $j -le 59 ]
  do
    echo $j
    ((j++))
  done
  ((i++))
  ((j=0))
done
