#!/usr/bin/env bash
# gives info about school file
school="school"
if test -e "$school"; then
  echo "school file exists"
  if test -s "$school"; then
    echo "school file is not empty"
  fi
  if test -f "$school"; then
    echo "school is a regular file"
  else
    echo "school file is empty"
  fi
else
  echo "school file does not exist"
fi
